#!/bin/bash
# Shared shell library for entrypoint.sh, first-start.sh and the `admin`
# CLI. Sourced, never executed directly.
#
# Schema/behaviour this was written against (iRedMail 1.8.8, MySQL/MariaDB
# backend): iRedMail/samples/iredmail/iredmail.mysql (domain, mailbox,
# forwardings, domain_admins tables), iRedMail/tools/create_mail_user_SQL.sh
# (password hashing + hashed maildir layout), iRedMail/samples/amavisd/
# amavisd.conf (dkim_key()/@dkim_signature_options_bysender_maps).
set -euo pipefail

SECRETS_DIR=/data/secrets
DKIM_DIR=/var/lib/dkim
AMAVIS_DKIM_INCLUDE=/etc/amavis/conf.d/60-dkim-domains
VMAIL_STORAGE_BASE=/var/vmail/vmail1

secret() {
    # secret <name> -> prints it, generating+persisting 0600 on first use.
    local f="${SECRETS_DIR}/$1"
    if [ ! -f "$f" ]; then
        mkdir -p "$SECRETS_DIR"
        openssl rand -hex 24 > "$f"
        chmod 0600 "$f"
    fi
    cat "$f"
}

# admin_cli DB user: least-privilege, only on vmail db (#57). Created by
# first-start.sh the first time the container ever boots.
mysql_admin() {
    mysql -uadmin_cli -p"$(secret mysql_admin_cli.pw)" -h 127.0.0.1 vmail "$@"
}

mysql_root() {
    mysql -uroot -p"$(secret mysql_root.pw)" -h 127.0.0.1 "$@"
}

mysqldump_root() {
    mysqldump -uroot -p"$(secret mysql_root.pw)" -h 127.0.0.1 "$@"
}

now_sql() { date '+%Y-%m-%d %H:%M:%S'; }

hash_password() {
    doveadm pw -s SSHA512 -p "$1"
}

# hashed_maildir <domain> <username> -> domain/a/b/c/username-<ts>/
hashed_maildir() {
    local domain="$1" user="$2" ts s1 s2 s3
    ts="$(date +%Y.%m.%d.%H.%M.%S)"
    s1="$(printf '%s' "$user" | cut -c1)"
    s2="$(printf '%s' "$user" | cut -c2)"; [ -z "$s2" ] && s2="$s1"
    s3="$(printf '%s' "$user" | cut -c3)"; [ -z "$s3" ] && s3="$s2"
    printf '%s/%s/%s/%s/%s-%s/' "$domain" "$s1" "$s2" "$s3" "$user" "$ts"
}

# quota_to_mb <1G|512M|...> -> integer MB, matches mailbox.quota's unit
# (iRedMail stores quota in MB; DEFAULT_QUOTA='1024' == 1GB, see
# tools/create_mail_user_SQL.sh).
quota_to_mb() {
    local q="$1" num unit
    num="$(echo "$q" | sed -E 's/[^0-9.]+$//')"
    unit="$(echo "$q" | sed -E 's/^[0-9.]+//' | tr 'a-z' 'A-Z')"
    case "$unit" in
        G|GB) awk -v n="$num" 'BEGIN{printf "%d", n*1024}' ;;
        M|MB|'') awk -v n="$num" 'BEGIN{printf "%d", n}' ;;
        K|KB) awk -v n="$num" 'BEGIN{printf "%d", (n/1024<1)?1:n/1024}' ;;
        *) echo "quota_to_mb: unknown unit in '$q'" >&2; exit 1 ;;
    esac
}

# --- DKIM ---------------------------------------------------------------
# generate_dkim_key <domain>: one 2048-bit RSA key per domain, never
# reused/shared across domains (#50/#92 - no wildcard key).
generate_dkim_key() {
    local domain="$1" key="${DKIM_DIR}/${domain}.pem"
    mkdir -p "$DKIM_DIR"
    if [ ! -f "$key" ]; then
        openssl genrsa -out "$key" 2048 >/dev/null 2>&1
    fi
    chown amavis:amavis "$key" 2>/dev/null || true
    chmod 0400 "$key"
}

# dkim_dns_record <domain> -> the exact TXT record value to publish at
# dkim._domainkey.<domain>.
dkim_dns_record() {
    local domain="$1" key="${DKIM_DIR}/${domain}.pem" pub
    pub="$(openssl rsa -in "$key" -pubout -outform DER 2>/dev/null | base64 -w0)"
    printf 'v=DKIM1; k=rsa; p=%s' "$pub"
}

# regenerate_amavis_dkim_include: rewrite the per-domain dkim_key() +
# @dkim_signature_options_bysender_maps block from the domain table - the
# single source of truth is the `domain` SQL table, this file is always
# fully regenerated (never hand-patched) so add/rm stay idempotent and
# restore-safe.
regenerate_amavis_dkim_include() {
    local domains tmp
    tmp="$(mktemp)"
    domains="$(mysql_admin -N -e "SELECT domain FROM domain WHERE active=1;")"
    {
        echo "# generated by /usr/local/bin/admin - do not hand-edit"
        for d in $domains; do
            generate_dkim_key "$d"
            echo "dkim_key('${d}', 'dkim', '${DKIM_DIR}/${d}.pem');"
        done
        echo '@dkim_signature_options_bysender_maps = ({'
        for d in $domains; do
            echo "    '${d}' => { d => '${d}', a => 'rsa-sha256', c => 'relaxed/simple', ttl => 30*24*3600 },"
        done
        echo '});'
        echo '1;'
    } > "$tmp"
    mkdir -p "$(dirname "$AMAVIS_DKIM_INCLUDE")"
    mv "$tmp" "$AMAVIS_DKIM_INCLUDE"
    chmod 0644 "$AMAVIS_DKIM_INCLUDE"
    supervisorctl -c /etc/supervisor/supervisord.conf restart amavis >/dev/null 2>&1 || true
}

mx_hostname() {
    cat /data/secrets/hostname 2>/dev/null || hostname -f
}

require_mountpoints() {
    # row 13 / #84: refuse to start on a mis-mounted (anonymous) volume
    # instead of silently writing into the container's writable layer.
    local p
    for p in /data/mysql /data/vmail /data/certs /data/overrides /data/secrets; do
        mkdir -p "$p"
        if ! mountpoint -q "$p"; then
            echo "FATAL: $p is not a mounted volume - refusing to start (fixes #84)." >&2
            exit 1
        fi
    done
}
