#!/bin/bash
# Runs on EVERY start, unlike first-start.sh (which runs once, gated by
# /data/secrets/.initialized). /etc and /opt are NOT volumes - they always
# come back from the image's pristine layer (TEMP_*_PASSWD placeholders,
# build.invalid hostname/domain) on a new container, even though
# /data/secrets/.initialized (a volume) says "already initialised". A
# plain `docker compose down` (no -v) + `up` creates exactly that: a new
# container, same volumes. Without re-rendering here, every service that
# authenticates to MariaDB with a config-file password (postfix, dovecot,
# sogo, amavis, iredapd, iredadmin) sends the literal string
# "TEMP_..._PASSWD" and every login/delivery breaks (row 13/#84 - found by
# testing `docker compose down` + `up`, not just "the volume must be
# real").
#
# Uses only what first-start.sh already persisted (hostname, mail_domain,
# the secrets/*.pw files) - never the current MAIL_DOMAIN/HOSTNAME_FQDN
# env vars, so passing a different MAIL_DOMAIN on a later start cannot
# silently re-point an already-initialised server (row 13).
set -euo pipefail
. /usr/local/lib/iredmail/common.sh

# Gate on hostname/mail_domain existing rather than .initialized: this
# script is also called from inside first-start.sh itself, before
# .initialized is touched (see there for why), so the domain/hostname
# secret files are the earlier and correct signal that first-start.sh has
# reached the point of knowing what to render.
[ -f "${SECRETS_DIR}/hostname" ] && [ -f "${SECRETS_DIR}/mail_domain" ] || exit 0

HOSTNAME_FQDN="$(cat "${SECRETS_DIR}/hostname")"
MAIL_DOMAIN="$(cat "${SECRETS_DIR}/mail_domain")"
BUILD_DOMAIN=build.invalid
BUILD_HOSTNAME=mail.build.invalid

echo "*** render-config: substituting runtime secrets into config files"
# -not -name '*.db': these greps rewrite *text* config files; the same
# byte-for-byte sed run against a Berkeley DB (aliases.db, transport.db -
# both contain 'build.invalid'/'mail.build.invalid' baked in at build time)
# changes the replaced string's length and corrupts the DB's internal
# offsets ("error: open database ...: Invalid argument" on every postfix
# smtpd start - row 1). transport.db is fully regenerated by
# peer-domains.sh; the two aliases databases are rebuilt below instead.
for pair in \
    "TEMP_VMAIL_DB_BIND_PASSWD:$(secret vmail_bind.pw)" \
    "TEMP_VMAIL_DB_ADMIN_PASSWD:$(secret vmail_admin.pw)" \
    "TEMP_MYSQL_ROOT_PASSWD:$(secret mysql_root.pw)" \
    "TEMP_AMAVISD_DB_PASSWD:$(secret amavisd.pw)" \
    "TEMP_IREDADMIN_DB_PASSWD:$(secret iredadmin.pw)" \
    "TEMP_SOGO_DB_PASSWD:$(secret sogo.pw)" \
    "TEMP_SOGO_SIEVE_MASTER_PASSWD:$(secret sogo_sieve.pw)" \
    "TEMP_IREDAPD_DB_PASSWD:$(secret iredapd.pw)" \
    "TEMP_MLMMJADMIN_API_AUTH_TOKEN:$(secret mlmmjadmin.pw)" \
; do
    placeholder="${pair%%:*}"; real="${pair#*:}"
    # `|| true`: this script runs twice on a first boot (once from inside
    # first-start.sh, once again from entrypoint.sh right after) and again
    # on every later boot - by the second/later run the placeholder is
    # already gone, `grep -r` finds nothing and exits 1, which `pipefail`
    # (set above) turned into the whole script dying mid-substitution,
    # every later placeholder left unreplaced.
    grep -rlZ -F "$placeholder" /etc /opt --exclude='*.db' 2>/dev/null | xargs -0 -r sed -i "s#${placeholder}#${real}#g" || true
done

echo "*** render-config: rewiring build-time placeholder hostname/domain -> ${HOSTNAME_FQDN}/${MAIL_DOMAIN}"
grep -rlZ -F "$BUILD_HOSTNAME" /etc /opt --exclude='*.db' 2>/dev/null | xargs -0 -r sed -i "s#${BUILD_HOSTNAME}#${HOSTNAME_FQDN}#g" || true
grep -rlZ -F "$BUILD_DOMAIN" /etc /opt --exclude='*.db' 2>/dev/null | xargs -0 -r sed -i "s#${BUILD_DOMAIN}#${MAIL_DOMAIN}#g" || true
hostname "$HOSTNAME_FQDN" 2>/dev/null || true

# Rebuild the two alias databases from their now-correctly-rewritten text
# sources (/etc/postfix/aliases, /etc/aliases) instead of leaving the
# build-time .db excluded above.
postalias /etc/postfix/aliases
newaliases

# TLS cert symlinks: /etc/ssl/{certs,private}/iRedMail.* are not on a
# volume either; /data/certs/{cert,key}.pem is. Recreate every start.
mkdir -p /etc/ssl/private
ln -sf /data/certs/cert.pem /etc/ssl/certs/iRedMail.crt
ln -sf /data/certs/key.pem /etc/ssl/private/iRedMail.key
